---
title: "Loops and Functions"
author: "Michelle Lam"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Part 1: For loops revisted

Task 1
```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
transects <- c("Transect A", "Transect B", "Transect C")

weekday_transect_out <- matrix(nrow = length(weekdays), ncol = length(transects)) 

for (i in seq_along(transects)) {
  for(j in seq_along(weekdays)) {
    out <- paste(weekdays[j], "-", transects[i])
    weekday_transect_out[j,i] <- out
  }
}
```

### Part 2: Functions introduced

Task 2
Write a function called force that calculates a force (in Newtons), given inputs of mass (in kg) and acceleration (in m/s2 (recall: F=ma), and returns a statement “The resulting force is ___ Newtons.”

```{r}
force <- function(mass, acceleration){
  print(paste("The resulting force is",mass * acceleration, "Newtons."))
}

force(mass = 5, acceleration = 4)

```

Task 3
legth:weight relationship
$$W = aL^b$$
L= total fish length (cm)
W = expected fish weight (grams)
a and b are species dependent
```{r}
fish_parms <- tribble(
  ~sci_name, ~common_name, ~a_est, ~b_est,
  "Chanos chanos", "Milkfish", 0.0905, 2.52,
  "Sphyraena barracuda", "Great barracuda", 0.0181, 0.327, 
  "Caranx ignobilis", "Giant trevally", 0.0353, 3.05
)

fish_weight <- function(fish_name, tot_length) {
  filter_by_name <- filter(fish_parms, common_name == fish_name)
  filter_by_name$a_est * ((tot_length)^filter_by_name$b_est)
}

fish_weight(fish_name = "Milkfish", tot_length = 10)

vec_length <- seq(from = 0, to = 100, by =1)

milkfish_weights <- fish_weight(fish_name = "Milkfish", tot_length = vec_length)

```

Task 4
$$Pdeep = 0.5H^2T$$

```{r}
wave_power <- function(H, T) {
  print(0.5 * (H^2) * T)
}

wave_heights <- seq(from = 0, to = 3, by = 0.2)

wave_power(T = 8, H = wave_heights)

```

$$Pshallow = 0.81H^2T$$

```{r}
wave_power_var_depth <- function(depth, H, T) {
  if (depth > 12) {
    print(0.5 * (H^2) * T)
    message("This outcome was calculated using the deep water equation for wave power (depth is greater than 12 meters)")
  }
  else if (depth <= 12) {
  print( 0.81 * (H^2) * T)
    message("This outcome was calculated using the shallow water equation for wave power (depth is less than or equal to 12 meters)")
  }
}

wave_power_var_depth(depth = 5, H = 5, T = 0.5)

```

